version: '3.8'

services:
  # 1. Ma'lumotlar bazasi konteyneri
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432" # Agar lokal IDE dan ulanmoqchi bo'lsang kerak
    volumes:
      - db_data:/var/lib/postgresql/data # DB ma'lumotlari o'chib ketmasligi uchun

  # 2. Spring Boot ilovamiz konteyneri
  # ... db, prometheus, grafana o'zgarishsiz qoladi ...

  app-blue:
    image: ghcr.io/abbostemirov/chatgpt-clone/spring-app:latest # O'zingni loginingni yoz
    container_name: spring_app_blue
    depends_on:
      - db
    restart: always
    healthcheck: # Konteyner yondimi yoki yo'qmi tekshiradi
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  app-green:
    image: ghcr.io/abbostemirov/chatgpt-clone/spring-app:latest # O'zingni loginingni yoz
    container_name: spring_app_green
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d # Butun nginx papkasini ulaymiz
    depends_on:
      - app-blue

  # ... (oldindan bor bo'lgan db, app, nginx xizmatlari turaversin) ...

  # 4. Prometheus (Ma'lumot yig'uvchi baza)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  # 5. Grafana (Chiroyli Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Kirish uchun parol
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  db_data: # Docker ichida virtual disk (xotira)