spring.config.import=optional:file:.env[.properties]
spring.application.name=chatgpt
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
# Docker Compose tarmog'ida 'db' nomli konteynerga ulanamiz (localhost emas!)
spring.datasource.url=jdbc:postgresql://db:5432/devdb
spring.datasource.username=devuser
spring.datasource.password=devpassword

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true