global:
  scrape_interval: 10s # Har 10 soniyada ma'lumotlarni yig'adi

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080'] # Docker tarmog'idagi Spring Boot ilovamiz