server {
    listen 80;
    server_name localhost;

    # Docker'ning ichki DNS serveri (xizmat nomlarini IP ga aylantirish uchun)
    resolver 127.0.0.11 valid=5s;

    # Qaysi biri aktivligini o'qiydigan fayl (yozgan scriptimiz shu faylni yangilaydi)
    include /etc/nginx/conf.d/active.conf*;

    location / {
        # So'rovlarni $active_app (blue yoki green) ga yuboramiz
        proxy_pass http://$active_app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}