name: CI/CD Pipeline to Multipass

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # DOCKER BUILD bosqichini olib tashlaymiz, uni endi docker-compose bajaradi.

      - name: Deploy with Docker Compose
        run: |
          # Oldingi ishlab turgan eski konteynerlarni to'xtatamiz va tozalaymiz
          docker compose down
          # Yangi kod asosida image'ni qayta build qilib, fonga (daemon) ishga tushiramiz
          docker compose up -d --build